# Generated by Django 3.2.4 on 2021-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feed_mail',
            field=models.EmailField(max_length=255),
        ),
    ]
