# Generated by Django 3.2.4 on 2021-07-04 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activist_appeal_observer_rescuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to=settings.AUTH_USER_MODEL),
        ),
    ]
