# Generated by Django 3.2.4 on 2021-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('U', 'Unsolved'), ('S', 'Solved')], max_length=1),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='type',
            field=models.CharField(choices=[('S', 'Study'), ('P', 'Project'), ('C', 'CTF')], max_length=1),
        ),
    ]
