# Generated by Django 3.2.4 on 2021-07-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210704_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(max_length=100),
        ),
    ]
